config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :quotes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
    
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end

    def archived?
        status == "archived"
    end
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, dependent: :destroy
  
  validates :title, presence: true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :title, presence: true

  # So consegui usar o callback sem a validação (?)
  before_validation :set_default_checked, unless: :is_checked?

  private

  def set_default_checked
    self.checked = false
  end

  def is_checked?
    self.checked == true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: :see_other
    end

    private
        def comment_params
            params.require(:comment).permit(:commenter, :body, :status)
        end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    # Para mostrar os erros de validação do model Task
    @task = @list.tasks.build
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update(list_params)
      redirect_to @list
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/quotes_controller.rb
# app/controllers/quotes_controller.rb

class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
    @quotes = Quote.all
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      redirect_to quotes_path, notice: "Quote was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @quote.update(quote_params)
      redirect_to quotes_path, notice: "Quote was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @quote.destroy
    redirect_to quotes_path, notice: "Quote was successfully destroyed."
  end

  private

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def create
        @list = List.find(params[:list_id])
        @task = @list.tasks.build(task_params)
        if @task.save
            redirect_to list_path(@list)
        else 
            # "lists/show" é o path para o template, não a URL
            render "lists/show", status: :unprocessable_entity
        end 
    end

    def edit
        @list = List.find(params[:list_id])
        @task = @list.tasks.find(params[:id])
    end

    def update
        @list = List.find(params[:list_id])
        @task = @list.tasks.find(params[:id])

        if @task.update(task_params)
            redirect_to @list
        else
            head :unprocessable_entity
        end
    end

    def destroy
        @list = List.find(params[:list_id])
        @task = @list.tasks.find(params[:id])
        @task.destroy

        redirect_to list_path(@list), status: :see_other
    end

    private

    def task_params
        params.require(:task).permit(:title, :checked)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% article.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
        <% article.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>

    <div>
        <%= form.submit %>
    </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
    <% @articles.each do |article| %>
        <% unless article.archived? %>
            <li>
                <%= link_to article.title, article %>
            </li>
        <% end %>
    <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
    <li><%= link_to "Edit", edit_article_path(@article) %></li>
    <li><%= link_to "Destroy", article_path(@article), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
    } %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
    <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
    </p>

    <p>
        <strong>Comment:</strong>
        <%= comment.body %>
    </p>

    <p>
        <%= link_to "Destroy Comment", [comment.article, comment],
        data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
        } %>
    </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
        <%= form.label :commenter %><br>
        <%= form.text_field :commenter %>
    </p>

    <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
    </p>

    <div>
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with model: list do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% list.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>

<% end %>

app/views/lists/_options.erb
<span class="list-options">
    <%= link_to "Edit Title", edit_list_path(@list) %> 
    |
    <%= link_to "All Lists", lists_path %>
</span>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render "form", list: @list %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<ul>
    <% @lists.each do |list| %>
        <li>
        <%= link_to list.title, list %>
        </li>
    <% end %>
</ul>

<%= link_to "Create New List", new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class="list-header">
    <h1 class="list-title"><%= @list.title %></h1>
    <%= render "lists/options" %>
</div>

<section class="task-list">
    <%= render "tasks/form", list: @list, task: @task %>

    <%= render @list.tasks.reverse %>
</section>

<%= button_to "Delete List", list_path(@list), method: :delete, 
    form: {data: {turbo_confirm: "Are you sure? You will lose all tasks."}}, 
    class: "delete-list" %>

app/views/quotes/_form.html.erb
<% # app/views/quotes/_form.html.erb %>

<%= simple_form_for quote, html: { class: "quote form" } do |f| %>
  <% if quote.errors.any? %>
    <div class="error-message">
      <%= quote.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/quotes/_quote.html.erb
<% # app/views/quotes/_quote.html.erb %>

<div class="quote">
  <%= link_to quote.name, quote_path(quote) %>
  <div class="quote__actions">
    <%= button_to "Delete",
                  quote_path(quote),
                  method: :delete,
                  class: "btn btn--light" %>
    <%= link_to "Edit",
                edit_quote_path(quote),
                class: "btn btn--light" %>
  </div>
</div>

app/views/quotes/edit.html.erb
<% # app/views/quotes/edit.html.erb %>

<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

  <div class="header">
    <h1>Edit quote</h1>
  </div>

  <%= render "form", quote: @quote %>
</main>

app/views/quotes/index.html.erb
<% # app/views/quotes/index.html.erb %>

<main class="container">
  <div class="header">
    <h1>Quotes</h1>
    <%= link_to "New quote",
                new_quote_path,
                class: "btn btn--primary" %>
  </div>

  <%= render @quotes %>
</main>

app/views/quotes/new.html.erb
<% # app/views/quotes/new.html.erb %>

<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>

  <div class="header">
    <h1>New quote</h1>
  </div>

  <%= render "form", quote: @quote %>
</main>

app/views/quotes/show.html.erb
<% # app/views/quotes/show.html.erb %>

<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>
      <%= @quote.name %>
    </h1>
  </div>
</main>

app/views/tasks/_form.html.erb
<%= form_with model: [list, task] do |form| %>
    <div>
        <%= form.text_field :title, placeholder: "New task" %>
        <% task.errors.full_messages.each do |message| %>
            <div><%= message %></div>
        <% end %>
        <%= form.submit %>
    </div>

<% end %>

app/views/tasks/_task.erb
<% unless task.created_at.nil? %>
<div class="task">
    <% status = if task.checked; then "[X]" else "[ ]" end %>
    <p><%= status %> <%= task.title %></p>
    <div class="task-options">
        <% status = if task.checked? then "Uncheck" else "Check" end%>
        <%= link_to status, 
            [task.list, task, task: { checked: !task.checked? }],
            data: { turbo_method: :patch } 
        %> 
        |
        <%= link_to "Edit", edit_list_task_path(task.list, task) %>
        |
        <%= link_to "Delete", [task.list, task], data: {
            turbo_method: :delete
        } %>
    </div>
</div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render "form", list: @list, task:@task %>

<%= link_to "Back", list_path(@list) %>